# Generated by Django 5.2.1 on 2025-07-02 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_journalentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
